// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX6WQbd-o0QT4FnfKe3HCkblqDruxX4Kg',
    appId: '1:286199777511:web:76781d1451cac8cc88fa42',
    messagingSenderId: '286199777511',
    projectId: 'taskify-9b266',
    authDomain: 'taskify-9b266.firebaseapp.com',
    storageBucket: 'taskify-9b266.firebasestorage.app',
    measurementId: 'G-05X12BS6T5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLl4Gc25fHwj6dDstg3O2X4EpyZ9tkflU',
    appId: '1:286199777511:android:933aa92f648e7c4488fa42',
    messagingSenderId: '286199777511',
    projectId: 'taskify-9b266',
    storageBucket: 'taskify-9b266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARSyVT7dpzXz4Bjki-zYI_Wsm-AHWi7jk',
    appId: '1:286199777511:ios:af880f80b0041f3588fa42',
    messagingSenderId: '286199777511',
    projectId: 'taskify-9b266',
    storageBucket: 'taskify-9b266.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARSyVT7dpzXz4Bjki-zYI_Wsm-AHWi7jk',
    appId: '1:286199777511:ios:af880f80b0041f3588fa42',
    messagingSenderId: '286199777511',
    projectId: 'taskify-9b266',
    storageBucket: 'taskify-9b266.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX6WQbd-o0QT4FnfKe3HCkblqDruxX4Kg',
    appId: '1:286199777511:web:17b458ad3a0e146488fa42',
    messagingSenderId: '286199777511',
    projectId: 'taskify-9b266',
    authDomain: 'taskify-9b266.firebaseapp.com',
    storageBucket: 'taskify-9b266.firebasestorage.app',
    measurementId: 'G-GE331DY0JN',
  );
}
